[tool.poetry]
name = "postgresqlbackup"
version = "0.1.0"
description = "backup postgresql"
authors = ["zhaoo lee <zhaoolee@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
